# 실행시키지 말 것

version: "3.8"

services:
  # 데이터베이스
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: healthcare
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: test123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # 웹용 백엔드
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - .env
    expose:
      - "3001"
    command: npm run start:dev

  # 모델 학습 및 서빙(fastAPI)
  backend-model:
    build:
      context: ./model
    container_name: model
    depends_on:
      - postgres
    env_file:
      - .env
    expose:
      - "3002"
    command: npm run start:dev

  # 랭체인(fastAPI)
  backend-langchain:
    build:
      context: ./langchain
    container_name: langchain
    depends_on:
      - postgres
    env_file:
      - .env
    expose:
      - "3003"
    command: npm run start:dev

  # 프론드엔트(모바일 최적화 필요)
  frontend:
    build:
      context: ./frontend # Next 프로젝트 폴더
    container_name: next_app
    expose:
      - "3000"
    command: npm run start # prod면 next start, dev면 next dev

  # 정적 웹서버
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    depends_on:
      - next
      - backend
      - model
      - frontend
    ports:
      - "80:80"
      - "3000:80" # 호스트 3000, 컨테이너 80 (nginx)
      - "443:443" # TLS 쓰면 유지
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
